openapi: 3.0.3
info:
  title: API Ping
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Vérifie la disponibilité du service
      responses:
        '200':
          description: Réponse trouvé
          content:
            text/plain:
              schema:
                type: string
                example: pong
